// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class DZOI_Vizim_ErrorJson
{
    [Key]
    public int Id { get; set; }

    public string NazivGreske { get; set; }

    public int? IdJson { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SistemskiDatum { get; set; }

    [ForeignKey("IdJson")]
    [InverseProperty("DZOI_Vizim_ErrorJson")]
    public virtual DZOI_Vizim_Json IdJsonNavigation { get; set; }
}