// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class DZOI_Vizim_Fajlovi
{
    [Key]
    public int Id { get; set; }

    public int? IdSpecifikacije { get; set; }

    [StringLength(128)]
    public string NazivFajla { get; set; }

    public int? StatusId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DatumPrebacivanja { get; set; }

    [ForeignKey("IdSpecifikacije")]
    [InverseProperty("DZOI_Vizim_Fajlovi")]
    public virtual DZOI_Vizim_Specifikacija IdSpecifikacijeNavigation { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("DZOI_Vizim_Fajlovi")]
    public virtual DZOI_Status Status { get; set; }
}