// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses
{
    public partial class DZOI_InsertSpecifikacijeRacunaFajlovaResult
    {
        public string Poruka { get; set; }
        public int Status { get; set; }
    }
}
