// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses
{
    public partial class DZOI_VratiFajloveZaPrebacivanjeResult
    {
        [StringLength(128)]
        public string UputBroj { get; set; }
        [StringLength(128)]
        public string NazivFajla { get; set; }
        public int? IdJson { get; set; }
        public int IdSpec { get; set; }
    }
}
