// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class DZOI_Vizim_StavkeRacuna
{
    [Key]
    public int Id { get; set; }

    public int? IdRacuna { get; set; }

    [StringLength(128)]
    public string StavkaId { get; set; }

    [Column(TypeName = "date")]
    public DateTime? UslugaDatum { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Popust { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PunaCena { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ZaIsplatu { get; set; }

    [StringLength(64)]
    public string Valuta { get; set; }

    public int? UslugaId { get; set; }

    [StringLength(128)]
    public string SaradnikId { get; set; }

    [StringLength(128)]
    public string SaradnikNaziv { get; set; }

    [StringLength(255)]
    public string LabNalazFajl { get; set; }

    [StringLength(255)]
    public string NalazFajl { get; set; }

    [StringLength(255)]
    public string Nalazsistematski { get; set; }

    [StringLength(512)]
    public string UslugaNaziv { get; set; }

    [ForeignKey("IdRacuna")]
    [InverseProperty("DZOI_Vizim_StavkeRacuna")]
    public virtual DZOI_Vizim_Racun IdRacunaNavigation { get; set; }
}