// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class DZOI_LogProcedureError
{
    [Key]
    public int Id { get; set; }

    [StringLength(255)]
    public string ErrorProcedure { get; set; }

    public string ErrorMessage { get; set; }

    public int? ErrorNumber { get; set; }

    public int? ErrorSeverity { get; set; }

    public int? ErrorState { get; set; }

    public int? ErrorLine { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ErrorDateTime { get; set; }
}