// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class DZOI_Vizim_Racun
{
    [Key]
    public int Id { get; set; }

    public int? IdSpecifikacije { get; set; }

    [StringLength(128)]
    public string RacunId { get; set; }

    [Column(TypeName = "date")]
    public DateTime? RacunDatum { get; set; }

    [StringLength(128)]
    public string RacunBrojFiskala { get; set; }

    [StringLength(128)]
    public string UputBroj { get; set; }

    [StringLength(128)]
    public string BrojKartice { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? UkupanIznos { get; set; }

    [StringLength(255)]
    public string RacunFajl { get; set; }

    [StringLength(255)]
    public string UputFajl { get; set; }

    [InverseProperty("IdRacunaNavigation")]
    public virtual ICollection<DZOI_Vizim_StavkeRacuna> DZOI_Vizim_StavkeRacuna { get; set; } = new List<DZOI_Vizim_StavkeRacuna>();

    [ForeignKey("IdSpecifikacije")]
    [InverseProperty("DZOI_Vizim_Racun")]
    public virtual DZOI_Vizim_Specifikacija IdSpecifikacijeNavigation { get; set; }
}