// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class DZOI_Vizim_Specifikacija
{
    [Key]
    public int Id { get; set; }

    [StringLength(128)]
    public string FakturaId { get; set; }

    [StringLength(128)]
    public string FakturaBroj { get; set; }

    public int? IdUstanove { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DatumFakture { get; set; }

    public string OpisJson { get; set; }

    public int? StatusId { get; set; }

    public int? IdJson { get; set; }

    [InverseProperty("IdSpecifikacijeNavigation")]
    public virtual ICollection<DZOI_Vizim_Fajlovi> DZOI_Vizim_Fajlovi { get; set; } = new List<DZOI_Vizim_Fajlovi>();

    [InverseProperty("IdSpecifikacijeNavigation")]
    public virtual ICollection<DZOI_Vizim_Racun> DZOI_Vizim_Racun { get; set; } = new List<DZOI_Vizim_Racun>();

    [ForeignKey("IdJson")]
    [InverseProperty("DZOI_Vizim_Specifikacija")]
    public virtual DZOI_Vizim_Json IdJsonNavigation { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("DZOI_Vizim_Specifikacija")]
    public virtual DZOI_Status Status { get; set; }
}