// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class DZOI_Vizim_Json
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string nazivJson { get; set; }

    public int? StatusId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SistemskiDatum { get; set; }

    [InverseProperty("IdJsonNavigation")]
    public virtual ICollection<DZOI_Vizim_Specifikacija> DZOI_Vizim_Specifikacija { get; set; } = new List<DZOI_Vizim_Specifikacija>();
}