// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class DZOI_Status
{
    [Key]
    public int Id { get; set; }

    [StringLength(512)]
    public string Naziv { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<DZOI_Vizim_Fajlovi> DZOI_Vizim_Fajlovi { get; set; } = new List<DZOI_Vizim_Fajlovi>();

    [InverseProperty("Status")]
    public virtual ICollection<DZOI_Vizim_Folder> DZOI_Vizim_Folder { get; set; } = new List<DZOI_Vizim_Folder>();

    [InverseProperty("Status")]
    public virtual ICollection<DZOI_Vizim_Json> DZOI_Vizim_Json { get; set; } = new List<DZOI_Vizim_Json>();

    [InverseProperty("Status")]
    public virtual ICollection<DZOI_Vizim_Specifikacija> DZOI_Vizim_Specifikacija { get; set; } = new List<DZOI_Vizim_Specifikacija>();
}