// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class DZOI_Vizim_Folder
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string nazivFoldera { get; set; }

    public int? StatusId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DatumPrebacivanja { get; set; }

    public int? IdJson { get; set; }

    public int? IdSpec { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("DZOI_Vizim_Folder")]
    public virtual DZOI_Status Status { get; set; }
}