// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses
{
    public partial interface IRazmenaDokumentacijeDb_ContextProcedures
    {
        Task<List<DZOI_InsertSpecifikacijeRacunaFajlovaResult>> DZOI_InsertSpecifikacijeRacunaFajlovaAsync(DataTable Specifikacije, DataTable Racuni, DataTable StavkeRacuna, DataTable Fajlovi, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DZOI_VratiFajloveZaPrebacivanjeResult>> DZOI_VratiFajloveZaPrebacivanjeAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
