// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class RazmenaDokumentacijeDb_Context : DbContext
{
    public RazmenaDokumentacijeDb_Context(DbContextOptions<RazmenaDokumentacijeDb_Context> options)
        : base(options)
    {
    }

    public virtual DbSet<DZOI_LogProcedureError> DZOI_LogProcedureError { get; set; }

    public virtual DbSet<DZOI_SpisakMetoda> DZOI_SpisakMetoda { get; set; }

    public virtual DbSet<DZOI_Status> DZOI_Status { get; set; }

    public virtual DbSet<DZOI_Vizim_ErrorJson> DZOI_Vizim_ErrorJson { get; set; }

    public virtual DbSet<DZOI_Vizim_Fajlovi> DZOI_Vizim_Fajlovi { get; set; }

    public virtual DbSet<DZOI_Vizim_Folder> DZOI_Vizim_Folder { get; set; }

    public virtual DbSet<DZOI_Vizim_Json> DZOI_Vizim_Json { get; set; }

    public virtual DbSet<DZOI_Vizim_Racun> DZOI_Vizim_Racun { get; set; }

    public virtual DbSet<DZOI_Vizim_Specifikacija> DZOI_Vizim_Specifikacija { get; set; }

    public virtual DbSet<DZOI_Vizim_StavkeRacuna> DZOI_Vizim_StavkeRacuna { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DZOI_Status>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Sta__3214EC07244A9EFC");
        });

        modelBuilder.Entity<DZOI_Vizim_ErrorJson>(entity =>
        {
            entity.Property(e => e.SistemskiDatum)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_DZOI_Vizim_ErrorJson_SistemskiDatum");
        });

        modelBuilder.Entity<DZOI_Vizim_Fajlovi>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC07F62C86C2");

            entity.HasOne(d => d.IdSpecifikacijeNavigation).WithMany(p => p.DZOI_Vizim_Fajlovi).HasConstraintName("FK__DZOI_Vizi__IdSpe__5AEE82B9");
        });

        modelBuilder.Entity<DZOI_Vizim_Racun>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC07CE61C473");

            entity.HasOne(d => d.IdSpecifikacijeNavigation).WithMany(p => p.DZOI_Vizim_Racun).HasConstraintName("FK__DZOI_Vizi__IdSpe__5EBF139D");
        });

        modelBuilder.Entity<DZOI_Vizim_Specifikacija>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC070E3B55CE");

            entity.HasOne(d => d.IdJsonNavigation).WithMany(p => p.DZOI_Vizim_Specifikacija).HasConstraintName("FK_DZOI_Vizim_Specifikacija_DZOI_Vizim_Json");
        });

        modelBuilder.Entity<DZOI_Vizim_StavkeRacuna>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC07276DD272");

            entity.HasOne(d => d.IdRacunaNavigation).WithMany(p => p.DZOI_Vizim_StavkeRacuna).HasConstraintName("FK__DZOI_Vizi__IdRac__619B8048");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}