// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses
{
    public partial class RazmenaDokumentacijeDb_Context
    {
        private IRazmenaDokumentacijeDb_ContextProcedures _procedures;

        public virtual IRazmenaDokumentacijeDb_ContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new RazmenaDokumentacijeDb_ContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IRazmenaDokumentacijeDb_ContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class RazmenaDokumentacijeDb_ContextProcedures : IRazmenaDokumentacijeDb_ContextProcedures
    {
        private readonly RazmenaDokumentacijeDb_Context _context;

        public RazmenaDokumentacijeDb_ContextProcedures(RazmenaDokumentacijeDb_Context context)
        {
            _context = context;
        }

        public virtual async Task<List<DZOI_InsertSpecifikacijeRacunaFajlovaResult>> DZOI_InsertSpecifikacijeRacunaFajlovaAsync(DataTable Specifikacije, DataTable Racuni, DataTable StavkeRacuna, DataTable Fajlovi, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Specifikacije",
                    Value = Specifikacije ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[Specifikacija]",
                },
                new SqlParameter
                {
                    ParameterName = "Racuni",
                    Value = Racuni ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[Racun]",
                },
                new SqlParameter
                {
                    ParameterName = "StavkeRacuna",
                    Value = StavkeRacuna ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[StavkeRacuna]",
                },
                new SqlParameter
                {
                    ParameterName = "Fajlovi",
                    Value = Fajlovi ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[Fajlovi]",
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<DZOI_InsertSpecifikacijeRacunaFajlovaResult>("EXEC @returnValue = [dbo].[DZOI_InsertSpecifikacijeRacunaFajlova] @Specifikacije = @Specifikacije, @Racuni = @Racuni, @StavkeRacuna = @StavkeRacuna, @Fajlovi = @Fajlovi", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<DZOI_VratiFajloveZaPrebacivanjeResult>> DZOI_VratiFajloveZaPrebacivanjeAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<DZOI_VratiFajloveZaPrebacivanjeResult>("EXEC @returnValue = [dbo].[DZOI_VratiFajloveZaPrebacivanje]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        private static DataTable ToDataTable<T>(IEnumerable<T> items)
        {
            var dataTable = new DataTable();
            var properties = typeof(T).GetProperties();

            foreach (var prop in properties)
            {
                var propertyType = prop.PropertyType;
                if (propertyType.IsGenericType && propertyType.GetGenericTypeDefinition() == typeof(Nullable<>))
                {
                    propertyType = Nullable.GetUnderlyingType(propertyType);
                }
                dataTable.Columns.Add(prop.Name, propertyType);
            }

            foreach (var item in items)
            {
                var values = new object[properties.Length];
                for (int i = 0; i < properties.Length; i++)
                {
                    values[i] = properties[i].GetValue(item) ?? DBNull.Value;
                }
                dataTable.Rows.Add(values);
            }

            return dataTable;
        }
    }
}
