// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class RazmenaDokumentacijeDb_Context : DbContext
{
    public RazmenaDokumentacijeDb_Context(DbContextOptions<RazmenaDokumentacijeDb_Context> options)
        : base(options)
    {
    }

    public virtual DbSet<DZOI_LogProcedureError> DZOI_LogProcedureError { get; set; }

    public virtual DbSet<DZOI_MediGroup_ErrorZip> DZOI_MediGroup_ErrorZip { get; set; }

    public virtual DbSet<DZOI_MediGroup_Zip> DZOI_MediGroup_Zip { get; set; }

    public virtual DbSet<DZOI_Status> DZOI_Status { get; set; }

    public virtual DbSet<DZOI_Vizim_ErrorJson> DZOI_Vizim_ErrorJson { get; set; }

    public virtual DbSet<DZOI_Vizim_Fajlovi> DZOI_Vizim_Fajlovi { get; set; }

    public virtual DbSet<DZOI_Vizim_Folder> DZOI_Vizim_Folder { get; set; }

    public virtual DbSet<DZOI_Vizim_Json> DZOI_Vizim_Json { get; set; }

    public virtual DbSet<DZOI_Vizim_Racun> DZOI_Vizim_Racun { get; set; }

    public virtual DbSet<DZOI_Vizim_Specifikacija> DZOI_Vizim_Specifikacija { get; set; }

    public virtual DbSet<DZOI_Vizim_StavkeRacuna> DZOI_Vizim_StavkeRacuna { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DZOI_LogProcedureError>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Log__3214EC07CF91B0EA");
        });

        modelBuilder.Entity<DZOI_MediGroup_ErrorZip>(entity =>
        {
            entity.Property(e => e.SistemskiDatum).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<DZOI_MediGroup_Zip>(entity =>
        {
            entity.HasOne(d => d.Status).WithMany(p => p.DZOI_MediGroup_Zip).HasConstraintName("FK_DZOI_MediGroup_Zip_DZOI_Status");
        });

        modelBuilder.Entity<DZOI_Status>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Sta__3214EC0704D22D14");
        });

        modelBuilder.Entity<DZOI_Vizim_ErrorJson>(entity =>
        {
            entity.Property(e => e.SistemskiDatum).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdJsonNavigation).WithMany(p => p.DZOI_Vizim_ErrorJson).HasConstraintName("FK_DZOI_Vizim_ErrorJson_DZOI_Vizim_Json");
        });

        modelBuilder.Entity<DZOI_Vizim_Fajlovi>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC07D131233A");

            entity.HasOne(d => d.IdSpecifikacijeNavigation).WithMany(p => p.DZOI_Vizim_Fajlovi).HasConstraintName("FK__DZOI_Vizi__IdSpe__3C69FB99");

            entity.HasOne(d => d.Status).WithMany(p => p.DZOI_Vizim_Fajlovi).HasConstraintName("FK__DZOI_Vizi__Statu__3D5E1FD2");
        });

        modelBuilder.Entity<DZOI_Vizim_Folder>(entity =>
        {
            entity.HasOne(d => d.Status).WithMany(p => p.DZOI_Vizim_Folder).HasConstraintName("FK_DZOI_Vizim_Folder_DZOI_Status");
        });

        modelBuilder.Entity<DZOI_Vizim_Json>(entity =>
        {
            entity.Property(e => e.SistemskiDatum).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Status).WithMany(p => p.DZOI_Vizim_Json).HasConstraintName("FK_DZOI_Vizim_Json_DZOI_Status");
        });

        modelBuilder.Entity<DZOI_Vizim_Racun>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC07F4AE1BB2");

            entity.HasOne(d => d.IdSpecifikacijeNavigation).WithMany(p => p.DZOI_Vizim_Racun).HasConstraintName("FK__DZOI_Vizi__IdSpe__403A8C7D");
        });

        modelBuilder.Entity<DZOI_Vizim_Specifikacija>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC07F1300A31");

            entity.HasOne(d => d.IdJsonNavigation).WithMany(p => p.DZOI_Vizim_Specifikacija).HasConstraintName("FK_DZOI_Vizim_Specifikacija_DZOI_Vizim_Json");

            entity.HasOne(d => d.Status).WithMany(p => p.DZOI_Vizim_Specifikacija).HasConstraintName("FK__DZOI_Vizi__Statu__412EB0B6");
        });

        modelBuilder.Entity<DZOI_Vizim_StavkeRacuna>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC07539E8DC1");

            entity.HasOne(d => d.IdRacunaNavigation).WithMany(p => p.DZOI_Vizim_StavkeRacuna).HasConstraintName("FK__DZOI_Vizi__IdRac__4316F928");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}