// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;

public partial class VizimIntegracijaDb_TestContext : DbContext
{
    public VizimIntegracijaDb_TestContext(DbContextOptions<VizimIntegracijaDb_TestContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DZOI_LogProcedureError> DZOI_LogProcedureError { get; set; }

    public virtual DbSet<DZOI_Status> DZOI_Status { get; set; }

    public virtual DbSet<DZOI_Vizim_Fajlovi> DZOI_Vizim_Fajlovi { get; set; }

    public virtual DbSet<DZOI_Vizim_Json> DZOI_Vizim_Json { get; set; }

    public virtual DbSet<DZOI_Vizim_Racun> DZOI_Vizim_Racun { get; set; }

    public virtual DbSet<DZOI_Vizim_Specifikacija> DZOI_Vizim_Specifikacija { get; set; }

    public virtual DbSet<DZOI_Vizim_StavkeRacuna> DZOI_Vizim_StavkeRacuna { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DZOI_LogProcedureError>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Log__3214EC079FE68EE9");
        });

        modelBuilder.Entity<DZOI_Status>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Sta__3214EC07A3CBC4F5");
        });

        modelBuilder.Entity<DZOI_Vizim_Fajlovi>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC07CB99584A");

            entity.HasOne(d => d.IdSpecifikacijeNavigation).WithMany(p => p.DZOI_Vizim_Fajlovi).HasConstraintName("FK__DZOI_Vizi__IdSpe__2F10007B");

            entity.HasOne(d => d.Status).WithMany(p => p.DZOI_Vizim_Fajlovi).HasConstraintName("FK__DZOI_Vizi__Statu__300424B4");
        });

        modelBuilder.Entity<DZOI_Vizim_Json>(entity =>
        {
            entity.Property(e => e.SistemskiDatum).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Status).WithMany(p => p.DZOI_Vizim_Json).HasConstraintName("FK_DZOI_Vizim_Json_DZOI_Status");
        });

        modelBuilder.Entity<DZOI_Vizim_Racun>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC079B2DB579");

            entity.HasOne(d => d.IdSpecifikacijeNavigation).WithMany(p => p.DZOI_Vizim_Racun).HasConstraintName("FK__DZOI_Vizi__IdSpe__4AB81AF0");
        });

        modelBuilder.Entity<DZOI_Vizim_Specifikacija>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC070A8FF919");

            entity.HasOne(d => d.Status).WithMany(p => p.DZOI_Vizim_Specifikacija).HasConstraintName("FK__DZOI_Vizi__Statu__267ABA7A");
        });

        modelBuilder.Entity<DZOI_Vizim_StavkeRacuna>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DZOI_Viz__3214EC079A0EC4B1");

            entity.HasOne(d => d.IdRacunaNavigation).WithMany(p => p.DZOI_Vizim_StavkeRacuna).HasConstraintName("FK__DZOI_Vizi__IdRac__4D94879B");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}