// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DZO_IntegracijaUstanovaDokumentacija_API.Models.DomainClasses
{
    public partial class VizimIntegracijaDb_Context
    {
        private IVizimIntegracijaDb_TestContextProcedures _procedures;

        public virtual IVizimIntegracijaDb_TestContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new VizimIntegracijaDb_ContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IVizimIntegracijaDb_TestContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DZOI_InsertSpecifikacijeRacunaFajlovaResult>().HasNoKey().ToView(null);
        }
    }

    public partial class VizimIntegracijaDb_ContextProcedures : IVizimIntegracijaDb_TestContextProcedures
    {
        private readonly VizimIntegracijaDb_Context _context;

        public VizimIntegracijaDb_ContextProcedures(VizimIntegracijaDb_Context context)
        {
            _context = context;
        }

        public virtual async Task<List<DZOI_InsertSpecifikacijeRacunaFajlovaResult>> DZOI_InsertSpecifikacijeRacunaFajlovaAsync(DataTable Specifikacije, DataTable Racuni, DataTable StavkeRacuna, DataTable Fajlovi, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Specifikacije",
                    Value = Specifikacije ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[Specifikacija]",
                },
                new SqlParameter
                {
                    ParameterName = "Racuni",
                    Value = Racuni ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[Racun]",
                },
                new SqlParameter
                {
                    ParameterName = "StavkeRacuna",
                    Value = StavkeRacuna ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[StavkeRacuna]",
                },
                new SqlParameter
                {
                    ParameterName = "Fajlovi",
                    Value = Fajlovi ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[Fajlovi]",
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<DZOI_InsertSpecifikacijeRacunaFajlovaResult>("EXEC @returnValue = [dbo].[DZOI_InsertSpecifikacijeRacunaFajlova] @Specifikacije, @Racuni, @StavkeRacuna, @Fajlovi", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
